/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as QrCodeForWifiRouteImport } from './routes/qr-code-for-wifi'
import { Route as QrCodeForRestaurantRouteImport } from './routes/qr-code-for-restaurant'
import { Route as QrCodeForInstagramRouteImport } from './routes/qr-code-for-instagram'
import { Route as QrCodeForBusinessCardRouteImport } from './routes/qr-code-for-business-card'
import { Route as QrCodeRouteImport } from './routes/qr-code'
import { Route as QrRouteImport } from './routes/qr'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as LinksIdRouteImport } from './routes/links.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodeForWifiRoute = QrCodeForWifiRouteImport.update({
  id: '/qr-code-for-wifi',
  path: '/qr-code-for-wifi',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodeForRestaurantRoute = QrCodeForRestaurantRouteImport.update({
  id: '/qr-code-for-restaurant',
  path: '/qr-code-for-restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodeForInstagramRoute = QrCodeForInstagramRouteImport.update({
  id: '/qr-code-for-instagram',
  path: '/qr-code-for-instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodeForBusinessCardRoute = QrCodeForBusinessCardRouteImport.update({
  id: '/qr-code-for-business-card',
  path: '/qr-code-for-business-card',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodeRoute = QrCodeRouteImport.update({
  id: '/qr-code',
  path: '/qr-code',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksIdRoute = LinksIdRouteImport.update({
  id: '/links/$id',
  path: '/links/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/qr': typeof QrRoute
  '/qr-code': typeof QrCodeRoute
  '/qr-code-for-business-card': typeof QrCodeForBusinessCardRoute
  '/qr-code-for-instagram': typeof QrCodeForInstagramRoute
  '/qr-code-for-restaurant': typeof QrCodeForRestaurantRoute
  '/qr-code-for-wifi': typeof QrCodeForWifiRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/links/$id': typeof LinksIdRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/qr': typeof QrRoute
  '/qr-code': typeof QrCodeRoute
  '/qr-code-for-business-card': typeof QrCodeForBusinessCardRoute
  '/qr-code-for-instagram': typeof QrCodeForInstagramRoute
  '/qr-code-for-restaurant': typeof QrCodeForRestaurantRoute
  '/qr-code-for-wifi': typeof QrCodeForWifiRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/links/$id': typeof LinksIdRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/qr': typeof QrRoute
  '/qr-code': typeof QrCodeRoute
  '/qr-code-for-business-card': typeof QrCodeForBusinessCardRoute
  '/qr-code-for-instagram': typeof QrCodeForInstagramRoute
  '/qr-code-for-restaurant': typeof QrCodeForRestaurantRoute
  '/qr-code-for-wifi': typeof QrCodeForWifiRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/links/$id': typeof LinksIdRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/qr'
    | '/qr-code'
    | '/qr-code-for-business-card'
    | '/qr-code-for-instagram'
    | '/qr-code-for-restaurant'
    | '/qr-code-for-wifi'
    | '/refund-policy'
    | '/signup'
    | '/terms'
    | '/links/$id'
    | '/u/$username'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/qr'
    | '/qr-code'
    | '/qr-code-for-business-card'
    | '/qr-code-for-instagram'
    | '/qr-code-for-restaurant'
    | '/qr-code-for-wifi'
    | '/refund-policy'
    | '/signup'
    | '/terms'
    | '/links/$id'
    | '/u/$username'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/qr'
    | '/qr-code'
    | '/qr-code-for-business-card'
    | '/qr-code-for-instagram'
    | '/qr-code-for-restaurant'
    | '/qr-code-for-wifi'
    | '/refund-policy'
    | '/signup'
    | '/terms'
    | '/links/$id'
    | '/u/$username'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  QrRoute: typeof QrRoute
  QrCodeRoute: typeof QrCodeRoute
  QrCodeForBusinessCardRoute: typeof QrCodeForBusinessCardRoute
  QrCodeForInstagramRoute: typeof QrCodeForInstagramRoute
  QrCodeForRestaurantRoute: typeof QrCodeForRestaurantRoute
  QrCodeForWifiRoute: typeof QrCodeForWifiRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  LinksIdRoute: typeof LinksIdRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-code-for-wifi': {
      id: '/qr-code-for-wifi'
      path: '/qr-code-for-wifi'
      fullPath: '/qr-code-for-wifi'
      preLoaderRoute: typeof QrCodeForWifiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-code-for-restaurant': {
      id: '/qr-code-for-restaurant'
      path: '/qr-code-for-restaurant'
      fullPath: '/qr-code-for-restaurant'
      preLoaderRoute: typeof QrCodeForRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-code-for-instagram': {
      id: '/qr-code-for-instagram'
      path: '/qr-code-for-instagram'
      fullPath: '/qr-code-for-instagram'
      preLoaderRoute: typeof QrCodeForInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-code-for-business-card': {
      id: '/qr-code-for-business-card'
      path: '/qr-code-for-business-card'
      fullPath: '/qr-code-for-business-card'
      preLoaderRoute: typeof QrCodeForBusinessCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-code': {
      id: '/qr-code'
      path: '/qr-code'
      fullPath: '/qr-code'
      preLoaderRoute: typeof QrCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links/$id': {
      id: '/links/$id'
      path: '/links/$id'
      fullPath: '/links/$id'
      preLoaderRoute: typeof LinksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  QrRoute: QrRoute,
  QrCodeRoute: QrCodeRoute,
  QrCodeForBusinessCardRoute: QrCodeForBusinessCardRoute,
  QrCodeForInstagramRoute: QrCodeForInstagramRoute,
  QrCodeForRestaurantRoute: QrCodeForRestaurantRoute,
  QrCodeForWifiRoute: QrCodeForWifiRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  LinksIdRoute: LinksIdRoute,
  UUsernameRoute: UUsernameRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
